### ISSUE TITLE
[Epic] Add support for notebook

### ISSUE THREAD

**Issue by tchaton** [Lightning-AI/lightning-hpo#42]
## 🚀 Feature

TODOS:
- [] (EA) Release [lightning-notebook](https://github.com/Lightning-AI/LAI-Jupyter-Component) to PyPI
- [] (EA) Add run notebook (https://github.com/Lightning-AI/lightning-hpo/issues/28)
- [] (EA) Add stop notebook (https://github.com/Lightning-AI/lightning-hpo/issues/29)
- [] Add restart notebook (https://github.com/Lightning-AI/lightning-hpo/issues/41)
