### ISSUE TITLE
[Epic] Support Sweeps

### ISSUE THREAD

**Issue by tchaton** [Lightning-AI/lightning-hpo#47]
### Motivation

TODOS:
- [] Delete Sweeps / Trials
- [] Stop Sweeps / Trials
- [] View Sweeps / Trials
- [] Mount s3 Drive to Sweep
